"""RedCell 协议层 —— 所有组件之间的契约。

改这里的任何结构都会波及靶场、执行器、检测器、bandit 和报告,
按 AGENTS.md §3,属于"难以回退的决策",改动前需先讨论。
"""

from redcell.protocols.adapter import (
    AdapterCapabilities,
    AdapterInput,
    AdapterOutput,
    DeliveryObservability,
    IdempotencySupport,
    Message,
    ResetScope,
    SideEffect,
    TargetAdapter,
    ToolCall,
    ToolResult,
    TraceMetadata,
)
from redcell.protocols.common import (
    REDCELL_PROTOCOL_VERSION,
    FindingStatus,
    ImpactStatus,
    ObservabilityLevel,
    RedCellModel,
    Role,
    SeverityLevel,
    SignalChannel,
    VulnerabilityCategory,
    new_id,
    uuid7,
)
from redcell.protocols.finding import Evidence, Finding, ViolationTriad
from redcell.protocols.policy import (
    ActorPolicy,
    ConstraintKind,
    ParameterConstraint,
    Policy,
    ProtectedDataKind,
    ProtectedDatum,
    SystemPromptFingerprint,
    ToolEffectKind,
    ToolPolicy,
    ToolRetrySemantics,
)
from redcell.protocols.run import Run, RunEvent, RunEventType, RunStatus
from redcell.protocols.strategy import (
    MAX_TURNS_CEILING,
    MEMORYLESS_OPERATORS,
    MutationOperator,
    PredictedStrength,
    Strategy,
    StrategyRequirements,
    TemplateSlot,
    select_applicable,
)
from redcell.protocols.trace import (
    Attempt,
    AttemptStopReason,
    CostRecord,
    ReproductionContext,
    SignalScore,
    Turn,
    build_attempt,
    compute_reward,
)

__all__ = [
    "MAX_TURNS_CEILING",
    "MEMORYLESS_OPERATORS",
    "REDCELL_PROTOCOL_VERSION",
    "ActorPolicy",
    "AdapterCapabilities",
    "AdapterInput",
    "AdapterOutput",
    "Attempt",
    "AttemptStopReason",
    "ConstraintKind",
    "CostRecord",
    "DeliveryObservability",
    "Evidence",
    "Finding",
    "FindingStatus",
    "IdempotencySupport",
    "ImpactStatus",
    "Message",
    "MutationOperator",
    "ObservabilityLevel",
    "ParameterConstraint",
    "Policy",
    "PredictedStrength",
    "ProtectedDataKind",
    "ProtectedDatum",
    "RedCellModel",
    "ReproductionContext",
    "ResetScope",
    "Role",
    "Run",
    "RunEvent",
    "RunEventType",
    "RunStatus",
    "SeverityLevel",
    "SideEffect",
    "SignalChannel",
    "SignalScore",
    "Strategy",
    "StrategyRequirements",
    "SystemPromptFingerprint",
    "TargetAdapter",
    "TemplateSlot",
    "ToolCall",
    "ToolEffectKind",
    "ToolPolicy",
    "ToolResult",
    "ToolRetrySemantics",
    "TraceMetadata",
    "Turn",
    "ViolationTriad",
    "VulnerabilityCategory",
    "build_attempt",
    "compute_reward",
    "new_id",
    "select_applicable",
    "uuid7",
]
